episodes/urls.py
from django.urls import path
from . import views

app_name = 'episodes'

urlpatterns = [
    path('<slug:ep_slug>', views.episode_detail, name='detail'),
    path('<slug:ep_slug>/edit/', views.edit_episode, name='edit'),
]

feedcast/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('podcasts/', include('podcasts.urls')),
    path('about', views.about),
    path('', views.home),
]

urlpatterns += staticfiles_urlpatterns()#if in debug mode

podcasts/urls.py
from django.urls import path, include
from . import views
from .feeds import PodcastFeed

app_name = 'podcasts'

urlpatterns = [
    path('', views.podcast_list, name='list'),
    path('<slug:slug>',views.podcast_detail, name='detail'),
    path('<slug:slug>/edit/', views.edit_podcast, name='edit'),
    path('<slug:slug>/episode/',include('episodes.urls','episodes')),
    path('<slug:slug>/rss/',PodcastFeed())
]

episodes/models.py
from django.db import models
from podcasts.models import Podcast


class Episode(models.Model):
    podcast = models.ForeignKey(Podcast, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    date_published = models.DateTimeField()
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def description_snippet(self):
        desc = self.description
        if len(desc) > 50:
            return desc[:50] + "..."
        return desc

podcasts/models.py
from django.db import models
from multiselectfield import MultiSelectField
# from pycountry import languages, countries
from uuid import uuid4

# LANGUAGE_CHOICES=
# COUNTRY_CHOICES=

class Podcast(models.Model):

    EPISODIC = "ep"
    SERIAL = "se"
    ITUNES_TYPE_CHOICES = (
        (EPISODIC, "Episodic"),
        (SERIAL, "Serial"),
    )

    title = models.CharField(max_length=20)
    slug = models.SlugField()
    description = models.TextField()
    # language = models.CharField(choices=LANGUAGE_CHOICES)
    #itunes_author
    #itunes_image
    itunes_explicit = models.BooleanField()
    itunes_category = models.CharField(max_length=20)#fix (also feed)
    # itunes_subcategories
    itunes_complete = models.BooleanField(default=False)
    itunes_type = models.CharField(choices=ITUNES_TYPE_CHOICES, max_length=8, default=EPISODIC)
    spotify_limit = models.PositiveSmallIntegerField(blank=True, null=True)
    # spotify_country = models.CharField(choices=COUNTRY_CHOICES)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def description_snippet(self):
        desc = self.description
        if len(desc) > 50:
            return desc[:50] + "..."
        return desc

episodes/views.py
from django.shortcuts import render
from .models import Episode
from podcasts.models import Podcast


def episode_detail(request, slug, ep_slug):
    podcast = Podcast.objects.get(slug=slug)
    episode = podcast.episode_set.get(slug=ep_slug)
    return render(request, 'episodes/episode_detail.html', {'podcast': podcast, 'episode': episode})


def edit_episode(request, slug, ep_slug):
    podcast = Podcast.objects.get(slug=slug)
    episode = podcast.episode_set.get(slug=ep_slug)
    if request.method == 'POST':
        #do stuff
        pass

    episode = Episode.objects.get(slug=slug)
    return render(request, 'episodes/episode_edit.html', {'episode': episode})

feedcast/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    return render(request,'about.html')

def home(request):
    return render(request, 'homepage.html')

podcasts/views.py
from django.shortcuts import render
from .models import Podcast


def podcast_list(request):
    podcasts = Podcast.objects.all().order_by('date_created') #filter by current user
    return render(request, 'podcasts/podcast_list.html', {'podcasts': podcasts})


def podcast_detail(request, slug):
    podcast = Podcast.objects.get(slug=slug)
    episodes = podcast.episode_set.all().order_by('date_published')
    return render(request, 'podcasts/podcast_detail.html', {'podcast': podcast, 'episodes': episodes})


def edit_podcast(request, slug):
    podcast = Podcast.objects.get(slug=slug)
    return render(request, 'podcasts/podcast_edit.html', {'podcast': podcast})

episodes/templates/episodes/episode_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>{% block title %}{{ episode.title }}{% endblock %}</h1>
<p>{{ episode.description }}</p>

{% endblock %}

episodes/templates/episodes/episode_edit.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>{% block title %}{{ episode.title }}{% endblock %}</h1>

{% endblock %}

podcasts/templates/podcasts/podcast_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div name="podcast">
        <h1>{% block title %}{{ podcast.title }}{% endblock %}</h1>
        <p>{{ podcast.description }}</p>
    </div>
    <div name="episodes">
        {% for episode in episodes %}
            <div class="episode">
                <h3><a href="{% url 'podcasts:episodes:detail' slug=podcast.slug ep_slug=episode.slug %}">{{ episode.title }}</a></h3>
                <p>{{ episode.description_snippet}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

podcasts/templates/podcasts/podcast_edit.html
{% extends 'base_layout.html' %}

{% block content %}
<div nam="podcast-edit">
    <p>(Edit {{podcast.title}} Here)</p>
</div>
{% endblock %}

podcasts/templates/podcasts/podcast_list.html
{% extends 'base_layout.html' %}

{% block content %}
 <h1> {% block title %} Your podcasts {% endblock %}</h1>
    <div class="podcasts">
        {% for podcast in podcasts %}
            <div class="podcast">
                <h2><a href="{% url 'podcasts:detail' slug=podcast.slug %}">#{{ podcast.title }}</a></h2>
                <p> {{ podcast.description_snippet}}</p>
                <date>{{ podcast.date_created }}</date>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<h1> {% block title%} About {% endblock%}</h1>
<p>This is just the start!!!</p>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %}</title>
</head>
<body>
    <div>
        <a href="/"> Home </a>
        <a href="/about"> About </a>
        <a href="{% url 'podcasts:list' %}"> Podcasts </a>

    </div>
    <div name="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
<footer>
    Footer
</footer>
 </html>

templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<h1> {% block title %} Home {% endblock %} </h1>
<p> Welcome to <b>FeedCast</b>! </p>
{% endblock %}